### ISSUE TITLE
media: On dark backgrounds, the white variant of the lambdaflake should be used

### ISSUE THREAD

**Issue by samueldr** [nixcon/2020.nixcon.org#38]
There is no "usage guidelines" yet for the logo, but this is part of what I have in mind for whenever I get around to writing up some.

Same with the text, it should be white since the lambdaflake will be.

Are the source files accessible for the broadcast media thingies? (and hopefully in an open format anyone can fix.)

I say "white", `#ffffff` can be used, but if desired, more "see-through" variants of white can be used (often times called grey on black backgrounds).

**Comment by vachi** [comment]
> Are the source files accessible for the broadcast media thingies? (and hopefully in an open format anyone can fix.)

Could you please explain what you mean by open format and media thingies sorry? The files shared are pngs, a mp4, and a gif. The source file itself is made in adobe xd

Please find the updated design here. 
[https://drive.google.com/drive/folders/1_U9sY3jnieaQ7ZHv8__0zTJQiLaNl-Gn](https://drive.google.com/drive/folders/1_U9sY3jnieaQ7ZHv8__0zTJQiLaNl-Gn)

In the Google Drive folder above, we have included the adobe xd source file.

Please let me know if this is what you are looking for. 
In terms of rights to the files. we can just release it under whatever license is approved by Nix Design group.

**Comment by samueldr** [comment]
Hi,

By "media thingies", I meant those files under `media`, exactly what you shared. I don't know their proper names. Are they bumpers? Ah, probably placeholders?

By open format, I was thinking about the authoring format. Since it's Adobe, the answer is "no". Though that's not a worry for this use case.

* * *

I will have to admit a bit of culpability here. I didn't leave enough information here, thinking there would be a dialogue or discussion before work would be done towards this.

Additionally, the guideline and white variant of the logo weren't available before [about now](https://github.com/NixOS/nixos-artwork/pull/58).

Though this logo output does not include the globe.

* * *

Yeah, the monochrome variant of the logo doesn't use a staggered colouring scheme for the snowflake branches.

I opened #40, which bakes in the white variant with the globe. There are two variants, coloured globe (untouched) and monochrome globe. The first comment to that PR has a (large) pre-rendered PNG and a PDF export.

Hopefully the PDF files play nicely with whichever Adobe tools they use. They can use the pre-rendered PNG to compare and see if things are wrong. Since it's way bigger than needed, if push comes to shove the pre-rendered PNG should also be usable to render those media files.

Your designer can rework the globe if they see fit, though the Nix logo, itself, shouldn't need any adjustments (other than opacity if needed).

* * *

As [the original logo is CC-BY](https://github.com/NixOS/nixos-artwork/tree/master/logo#license), this variant of the logo ought to be. Now, the media files themselves I don't think they need to be CC-BY. Though it would be a fine license to use. Otherwise any similar type of license that can be used for artwork would probably be fine.

Hope this helps! And thanks for looking! Don't hesitate to ask if you have any questions.

**Comment by vachi** [comment]
Thank you for the clarifications. 

We are waiting for the svg version of the RelationalAI logo. Once we have that we will update the Nix logo as well to the monochrome version from #40. 

CC-BY is fine by us. Should we do a PR to nixos-artwork, or just PR to 2020.nixcon.org?
Meaning where should we deliver the work product in the end. 

Thanks,

**Comment by addict3d** [comment]
> CC-BY is fine by us. Should we do a PR to nixos-artwork, or just PR to 2020.nixcon.org?
> Meaning where should we deliver the work product in the end.

Please PR it here.

Thank you!

**Comment by samueldr** [comment]
Yeah, this is not by the NixOS org, so to the event's repo is the way to go.
